#!/bin/bash

#
#This program pack it with driver and srouce
#


function DeleteLanguage()
{
	mv ./temp/WebServer/script/main.js ./temp/WebServer/script/tempmain.js
	sed "s/g_langName = "\"$1\""/g_langName = "\"english_us\""/g" ./temp/WebServer/script/tempmain.js > ./temp/WebServer/script/tempmain2.js
	sed "/$1/d" ./temp/WebServer/script/tempmain2.js > ./temp/WebServer/script/main.js
	rm ./temp/WebServer/script/tempmain.js
	rm ./temp/WebServer/script/tempmain2.js
}




function ChangeInterface()
{
	command="s/ChangeInterface(.*,.*,.*,.*);/ChangeInterface($1,$2,$3,$4);/g"
	sed $command login.js > new.js
	rm login.js 
	mv new.js login.js
}



rm ./temp -rf
mkdir ./temp

mkdir ./temp/product/
cp ./product/productcheck  ./temp/	
cp ./product/boot.sh       ./temp/boot.sh       && dos2unix ./temp/boot.sh       && chmod 777 ./temp/boot.sh

if [ $1 -eq 28 ]
then
cp ./product/preupgrade_nbkc.sh.GM8283 ./temp/preupgrade.sh && dos2unix ./temp/preupgrade.sh && chmod 777 ./temp/preupgrade.sh
cp ./product/netupgrade_nbkc.sh.GM8283 ./temp/netupgrade.sh && dos2unix ./temp/netupgrade.sh && chmod 777 ./temp/netupgrade.sh
else
cp ./product/preupgrade_nbkc.sh ./temp/preupgrade.sh && dos2unix ./temp/preupgrade.sh && chmod 777 ./temp/preupgrade.sh
cp ./product/netupgrade_nbkc.sh ./temp/netupgrade.sh && dos2unix ./temp/netupgrade.sh && chmod 777 ./temp/netupgrade.sh
fi

if [ $1 -eq 27 ]
then
cp ./product/preupgrade_nbkc.sh.GM8283 ./temp/preupgrade.sh && dos2unix ./temp/preupgrade.sh && chmod 777 ./temp/preupgrade.sh
cp ./product/netupgrade_nbkc.sh.GM8283 ./temp/netupgrade.sh && dos2unix ./temp/netupgrade.sh && chmod 777 ./temp/netupgrade.sh
else
cp ./product/preupgrade_nbkc.sh ./temp/preupgrade.sh && dos2unix ./temp/preupgrade.sh && chmod 777 ./temp/preupgrade.sh
cp ./product/netupgrade_nbkc.sh ./temp/netupgrade.sh && dos2unix ./temp/netupgrade.sh && chmod 777 ./temp/netupgrade.sh
fi

if [ $4 -eq 25 ]
then
cp ./product/language2/ ./temp/ -rf && rm ./temp/language2/.svn/ -rf
mv ./temp/language2 ./temp/language
else
cp ./product/language/ ./temp/ -rf && rm ./temp/language/.svn/ -rf
if (( $4 != 11 && $4 != 18 && $4 != 12 ))
then
echo "用阿拉伯语替换芬兰语"
cp ./product/language2/arabic.dat ./temp/language
rm ./temp/language/finnish.dat
fi
fi
mkdir ./temp/config/

###################################处理UI部分##############################################
#####第一步：颜色
if [ $2 -eq 1 ]
then
cp ./product/ui_1/ ./temp/ui/ -rf && rm ./temp/ui/.svn/ -rf
fi

if [ $2 -eq 2 ]
then
cp ./product/ui_2/ ./temp/ui/ -rf && rm ./temp/ui/.svn/ -rf
fi

if [ $2 -eq 3 ]
then
cp ./product/ui_3/ ./temp/ui/ -rf && rm ./temp/ui/.svn/ -rf
fi

if [ $2 -eq 4 ]
then
cp ./product/ui_4/ ./temp/ui/ -rf && rm ./temp/ui/.svn/ -rf
fi

if [ $2 -eq 5 ]
then
cp ./product/ui_5/ ./temp/ui/ -rf && rm ./temp/ui/.svn/ -rf
fi

if [ $2 -eq 6 ]
then
cp ./product/ui_6/ ./temp/ui/ -rf && rm ./temp/ui/.svn/ -rf
fi

if [ $2 -eq 7 ]
then
cp ./product/ui_7/ ./temp/ui/ -rf && rm ./temp/ui/.svn/ -rf
fi

if [ $2 -eq 8 ]
then
cp ./product/ui_8/ ./temp/ui/ -rf && rm ./temp/ui/.svn/ -rf
fi

if [ $2 -eq 9 ]
then
cp ./product/ui_9/ ./temp/ui/ -rf && rm ./temp/ui/.svn/ -rf
fi

#####第二步：图片内容———选择菜单或者工具条形式、按钮或者锚的形式。
cp ./temp/ui/ui_common/* ./temp/ui/ -rf && rm ./temp/ui/ui_common/ -rf

if [ $3 -eq 1 ]
then
	cp ./temp/ui/ui_toolbar/* ./temp/ui/ -rf && rm ./temp/ui/ui_toolbar/ -rf
	cp ./temp/ui/ui_normal/* ./temp/ui/ -rf && rm ./temp/ui/ui_normal/ -rf
	rm ./temp/ui/ui_menu/ -rf && rm ./temp/ui/ui_anchor/ -rf
fi

if [ $3 -eq 2 ]
then
	cp ./temp/ui/ui_menu/* ./temp/ui/ -rf && rm ./temp/ui/ui_menu/ -rf
	cp ./temp/ui/ui_normal/* ./temp/ui/ -rf && rm ./temp/ui/ui_normal/ -rf
	rm ./temp/ui/ui_toolbar/ -rf && rm ./temp/ui/ui_anchor/ -rf
fi

if [ $3 -eq 3 ]
then
	cp ./temp/ui/ui_toolbar/* ./temp/ui/ -rf && rm ./temp/ui/ui_toolbar/ -rf
	cp ./temp/ui/ui_anchor/* ./temp/ui/ -rf && rm ./temp/ui/ui_anchor/ -rf
	rm ./temp/ui/ui_menu/ -rf && rm ./temp/ui/ui_normal/ -rf
fi

if [ $3 -eq 4 ]
then
	cp ./temp/ui/ui_menu/* ./temp/ui/ -rf && rm ./temp/ui/ui_menu/ -rf
	cp ./temp/ui/ui_anchor/* ./temp/ui/ -rf && rm ./temp/ui/ui_anchor/ -rf
	rm ./temp/ui/ui_toolbar/ -rf && rm ./temp/ui/ui_normal/ -rf
fi
#####################################处理客户端与播放器相关内容####################################
mkdir ./temp/WebServer
cp ./product/WebSites/* ./temp/WebServer/ -rf 
rm ./temp/WebServer/Plugin   -rf
rm ./temp/WebServer/UI_blue   -rf
rm ./temp/WebServer/css_style   -rf
rm ./temp/WebServer/logo  -rf
rm ./temp/WebServer/res   -rf

mkdir ./temp/VideoPlay
mkdir ./temp/WebSites
mkdir ./temp/WebSites/logo

#NVR使用NVR的LOGO
if [ $5 -eq 9 ]
then
	cp ./temp/ui/ui_logo/icon_logo_nvr.bmp ./temp/ui/ui_logo/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_nvr.bmp ./temp/ui/ui_logo/icon_logo_trans.bmp -rf
fi

#custom
if [ $4 -eq 1 ]
then
	#国际标准版
	echo "国际标准版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayIN/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf

	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/
	
	DeleteLanguage Danish

	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

fi

if [ $4 -eq 2 ] 
then
	#国内版本，同为品牌
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf	

fi

if [ $4 -eq 3 ] 
then
	#
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf
	
fi

if [ $4 -eq 4 ] 
then
	#US02
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/Plugin/TimeStampUS02/*     ./temp/WebServer/  -rf	
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_qsee/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
		
	cp ./temp/ui/ui_logo/icon_logo_qsee.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_qsee.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf

	#***************************us02 new***********************************
	#罗马语替换成印度利西亚语
	cp ./product/language3/romanian.dat ./temp/language/ -f 

	rm ./temp/language/indonesia.dat -f
	rm ./temp/WebServer/language/indonesian -rf
	DeleteLanguage indonesian

	#website定制
	cp ./product/WebSites/UI_blue/OEM/US02/*  ./temp/WebServer/ -rf
	sed "s/var g_US02 = false;/var g_US02 = true;/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js
	
fi

if [ $4 -eq 5 ] 
then
	#RU04
	cp ./product/WebSites/Plugin/CellPhoneRU04/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_ru04/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf

	
	#rm ./temp/WebServer/WebClientPlugin.pkg
		
	cp ./temp/ui/ui_logo/icon_logo_ru04.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_ru04.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
	
	cp  ./product/VideoPlay/VideoPlayRu04/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf	
	
	rm ./temp/language/russian.dat
	rm ./temp/WebServer/language/russian_ru -rf
	
	cp ./product/WebSites/Plugin/ScriptRU04/main.js ./temp/WebServer/script/main.js
	cp ./product/WebSites/Plugin/ScriptRU04/body_basic_config.html  ./temp/WebServer/body_html/body_basic_config.html
	cp ./product/WebSites/Plugin/ScriptRU04/WebClient.ico   ./temp/WebServer/res/WebClient.ico
	

fi


if [ $4 -eq 6 ] 
then
	#BR27
	cp ./product/WebSites/Plugin/CellPhonePortugal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/Plugin/TimeStampBR27/*     ./temp/WebServer/    -rf	
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_br27/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
		
	cp ./temp/ui/ui_logo/icon_logo_br27.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_br27.bmp ./temp/ui/icon_logo_trans.bmp -rf	
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayBR27/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
		
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf
	
	#BR27版本去掉中文简体、中文繁体、日语，用韩语替代
	rm ./temp/language/chinese_b.dat
	rm ./temp/WebServer/language/chinese_cht -rf
	rm ./temp/language/chinese_s.dat
	rm ./temp/WebServer/language/chinese_prc -rf
	rm ./temp/language/japanese.dat
	rm ./temp/WebServer/language/japanese -rf

	#拷贝韩语字库
	cp ./product/font/font_korean.dat ./temp/ui/font.dat
	cp ./product/language2/korean.dat ./temp/language/
	
	DeleteLanguage chinese_prc
	DeleteLanguage chinese_cht
	DeleteLanguage japanese

	sed "s/chinese_prc/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/chinese_cht/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/japanese/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js
	
	sed "s/var g_bBR27 = false/var g_bBR27 = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js
fi

if [ $4 -eq 7 ] 
then
	#TW01 不带数字签名的版本
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/Plugin/TimeStampTW01/*    ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf
	
fi

if [ $4 -eq 8 ] 
then
	#GB14
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf	
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf

fi

if [ $4 -eq 9 ] 
then
	#IN23
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_in23/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo_in23.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_in23.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf
	

fi

if [ $4 -eq 10 ] 
then
	#US47
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/Plugin/TimeStampSpeco/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_speco/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo_speco.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_speco.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayUS47/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf
	

fi

if [ $4 -eq 11 ]
then
        #IN25(ADI)
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_adi/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo_adi.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_adi.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayIN25/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf
	


fi

if [ $4 -eq 12 ]
then
        #PL14
	echo "PL14"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/Plugin/TimeStampPL14/*     ./temp/WebServer/  -rf	
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_pl14/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg

	cp ./temp/ui/ui_logo/icon_logo_pl14.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_pl14.bmp ./temp/ui/icon_logo_trans.bmp -rf	
	rm ./temp/ui/ui_logo -rf

	cp  ./product/VideoPlay/VideoPlayPL14/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf

	#pl14版本添加罗马尼亚语，去掉印尼语
	rm ./temp/language/indonesia.dat
	rm ./temp/WebServer/language/indonesian -rf

	#拷贝罗马尼亚语
	cp ./product/language3/romanian.dat ./temp/language/
	
	DeleteLanguage indonesian

	sed "s/indonesian/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian2 = false/var g_bHasRomanian2 = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js


fi

if [ $4 -eq 13 ] 
then
	#TW01 带数字签名的版本
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/Plugin/TimeStampTW01/*     ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf
	

fi

if [ $4 -eq 14 ] 
then
	#IL03
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_il03/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo_il03.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_il03.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf
	

fi

if [ $4 -eq 15 ] 
then
	#LV01
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf

fi


if [ $4 -eq 16 ] 
then
	#SHANGHAI
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf

fi


if [ $4 -eq 17 ] 
then
	#CBC 不带数字签名的版本
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/Plugin/NoTimeStamp/*    ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_cbc/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo_cbc.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_cbc.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf

fi
if [ $4 -eq 18 ] 
then
	#gb31
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_gb31/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo_gb31.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_gb31.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayIN25/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf
	
fi

if [ $4 -eq 20 ] 
then
	#国内版本，同为品牌
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf	
	
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
		
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf
fi



if [ $4 -eq 21 ] 
then
	#远征
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf	

fi

if [ $4 -eq 22 ] 
then
	#US02 日语版本
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/Plugin/TimeStampUS02/*     ./temp/WebServer/  -rf	
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_qsee/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
		
	cp ./temp/ui/ui_logo/icon_logo_qsee.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_qsee.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf
	
fi

if [ $4 -eq 23 ] 
then
	#国内版本，同为品牌
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf	

fi

if [ $4 -eq 24 ] 
then
	#国内版本，同为品牌
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf	

fi

if [ $4 -eq 25 ] 
then
	#TW01 日立版 不带数字签名的版本
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf	
	cp ./product/WebSites/Plugin/NoTimeStamp/*    ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	#拷贝日立字库
	cp ./product/font/font_japanese_MS_Gothic.dat ./temp/ui/font.dat
	
	cp ./temp/ui/ui_logo/icon_logo_rili.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans_rili.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
	
	cp  ./product/VideoPlay/VideoPlayHITACHI/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf
	
fi

if [ $4 -eq 26 ] 
then
	#国内版本，国标软件
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf	
	
	cp  ./product/VideoPlay/VideoPlayNormal/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat	
	rm ./temp/WebServer/language/russian_ru_d -rf	

fi

if [ $4 -eq 27 ]
then
	#国际标准版
	echo "国际标准版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	cp ./product/WebSites/Plugin/znv/*    ./temp/WebServer/  -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayIN/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#中兴力维版本客户端带二维码功能
	rm ./temp/WebServer/body_html/body_basic_info.html
	mv ./temp/WebServer/body_html/body_basic_info_znv.html ./temp/WebServer/body_html/body_basic_info.html
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf

	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/
	
	DeleteLanguage Danish

	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

fi

if [ $4 -eq 28 ]
then
	#国际标准版
	echo "国际标准版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	cp ./product/WebSites/Plugin/znv/*    ./temp/WebServer/  -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayIN/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#中兴力维版本客户端带二维码功能
	rm ./temp/WebServer/body_html/body_basic_info.html
	mv ./temp/WebServer/body_html/body_basic_info_znv.html ./temp/WebServer/body_html/body_basic_info.html
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf

	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/
	
	DeleteLanguage Danish

	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

fi

if [ $4 -eq 29 ]
then
	#国际标准版
	echo "国际标准版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	cp ./product/WebSites/Plugin/znvsc/*    ./temp/WebServer/  -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayIN/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf

	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/
	
	DeleteLanguage Danish

	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

fi

if [ $4 -eq 30 ]
then
	#国际标准版
	echo "国际标准版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	cp ./product/WebSites/Plugin/znv/*    ./temp/WebServer/  -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayIN/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#中兴力维版本客户端带二维码功能
	rm ./temp/WebServer/body_html/body_basic_info.html
	mv ./temp/WebServer/body_html/body_basic_info_znv.html ./temp/WebServer/body_html/body_basic_info.html
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf

	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/
	
	DeleteLanguage Danish

	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

fi

if [ $4 -eq 31 ]
then
	#国际标准版
	echo "国际标准版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/logo_CNB/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	cp ./temp/WebServer/reses/res_CNB/* ./temp/WebServer/res/
	rm ./temp/WebServer/reses -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayIN/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf

	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/
	
	DeleteLanguage Danish

	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

fi

if [ $4 -eq 32 ]
then
	#韩语标准版
	echo "韩语标准版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayKR/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf

	#去掉中文简体、中文繁体、日语，用韩语替代
	rm ./temp/language/chinese_b.dat
	rm ./temp/WebServer/language/chinese_cht -rf
	rm ./temp/language/chinese_s.dat
	rm ./temp/WebServer/language/chinese_prc -rf
	rm ./temp/language/japanese.dat
	rm ./temp/WebServer/language/japanese -rf

	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/

	#拷贝韩语字库
	cp ./product/font/font_korean.dat ./temp/ui/font.dat
	cp ./product/language2/korean.dat ./temp/language/
	
	DeleteLanguage Danish

	DeleteLanguage chinese_prc
	DeleteLanguage chinese_cht
	DeleteLanguage japanese

	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/chinese_prc/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/chinese_cht/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/japanese/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js
	
	sed "s/g_KoreaLangOEM = false/g_KoreaLangOEM = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js


fi

if [ $4 -eq 33 ]
then
	#kr24中文版
	echo "kr24中文版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/Plugin/kr24/* ./temp/WebServer/ -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayKR/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf


	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/

	
	DeleteLanguage Danish


	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js
fi

if [ $4 -eq 34 ]
then
	#kr24标准版
	echo "kr24标准版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/Plugin/kr24/* ./temp/WebServer/ -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayKR/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf

	#去掉中文简体、中文繁体、日语，用韩语替代
	rm ./temp/language/chinese_b.dat
	rm ./temp/WebServer/language/chinese_cht -rf
	rm ./temp/language/chinese_s.dat
	rm ./temp/WebServer/language/chinese_prc -rf
	rm ./temp/language/japanese.dat
	rm ./temp/WebServer/language/japanese -rf

	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/

	#拷贝韩语字库
	cp ./product/font/font_korean.dat ./temp/ui/font.dat
	cp ./product/language2/korean.dat ./temp/language/
	
	DeleteLanguage Danish

	DeleteLanguage chinese_prc
	DeleteLanguage chinese_cht
	DeleteLanguage japanese

	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/chinese_prc/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/chinese_cht/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/japanese/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js
	
	sed "s/g_KoreaLangOEM = false/g_KoreaLangOEM = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js
fi

#custom
if [ $4 -eq 35 ]
then
	#国际标准版
	echo "国际标准版"
	cp ./product/WebSites/Plugin/CellPhoneNormal/*   ./temp/WebServer/  -rf
	cp ./product/WebSites/UI_blue/*   ./temp/WebServer/  -rf
	cp ./temp/WebServer/logos/normal_logo/* ./temp/WebSites/logo/ -rf
	rm ./temp/WebServer/logos/ -rf
	
	#rm ./temp/WebServer/WebClientPlugin.pkg
	
	cp ./temp/ui/ui_logo/icon_logo.bmp ./temp/ui/icon_logo.bmp -rf
	cp ./temp/ui/ui_logo/icon_logo_trans.bmp ./temp/ui/icon_logo_trans.bmp -rf
	rm ./temp/ui/ui_logo -rf
		
	cp  ./product/VideoPlay/VideoPlayIN/*  ./temp/VideoPlay/ -rf && rm ./temp/VideoPlay/.svn -rf
	
	rm ./temp/language/russian_d.dat
	rm ./temp/WebServer/language/russian_ru_d -rf	
	
	#国际标准版本添加罗马尼亚语，去掉丹麦语
	rm ./temp/language/danish.dat
	rm ./temp/WebServer/language/Danish -rf

	#拷贝罗马尼亚语
	cp ./product/language2/romanian.dat ./temp/language/
	
	DeleteLanguage Danish

	sed "s/Danish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasRomanian = false/var g_bHasRomanian = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

fi

if [ $4 -ne 6 ] && [ $4 -ne 32 ] && [ $4 -ne 34 ]
then
echo "不是BR27或韩语版本删除客户端韩语"
rm ./temp/WebServer/language/Korean -rf
fi


if (( $4 != 11 && $4 != 18  && $4 != 12 ))
then
echo "不是IN25和GB31的去掉芬兰语相关"
	DeleteLanguage Finnish

	sed "s/Finnish/english_us/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js

	sed "s/var g_bHasArabic = false/var g_bHasArabic = true/" ./temp/WebServer/script/main.js > ./temp/WebServer/script/tmp.js
	mv ./temp/WebServer/script/tmp.js ./temp/WebServer/script/main.js
fi


#####################################转换文件格式，防止格式不兼容##########################
dos2unix ./temp/WebServer/server.js
dos2unix ./temp/WebServer/StringTable.xls
dos2unix ./temp/WebServer/webcamera.html
dos2unix ./temp/WebServer/runtime_log.html

dos2unix ./temp/WebServer/body_html/*
dos2unix ./temp/WebServer/css_style/*
dos2unix ./temp/WebServer/script/*

dos2unix ./temp/WebServer/language/chinese_prc/*
dos2unix ./temp/WebServer/language/english_us/*
dos2unix ./temp/WebServer/language/chinese_cht/*
dos2unix ./temp/WebServer/language/bulgarian/*
dos2unix ./temp/WebServer/language/Czech/*
dos2unix ./temp/WebServer/language/french_fr/*
dos2unix ./temp/WebServer/language/germany/*
dos2unix ./temp/WebServer/language/greek/*
dos2unix ./temp/WebServer/language/hebrew/*
dos2unix ./temp/WebServer/language/italian/*
dos2unix ./temp/WebServer/language/polish/*
dos2unix ./temp/WebServer/language/portuguese/*
dos2unix ./temp/WebServer/language/russian_ru/*
dos2unix ./temp/WebServer/language/russian_ru_d/*
dos2unix ./temp/WebServer/language/Spanish/*
dos2unix ./temp/WebServer/language/turkish_tr/*
dos2unix ./temp/WebServer/language/thai/*
dos2unix ./temp/WebServer/language/Hungarian/*
dos2unix ./temp/WebServer/language/Lithuania/*

#korean
dos2unix ./temp/WebServer/language/Korean/*

cp ./project/lib/libtsnetdevice.so ./temp/



#防止还有.svn
rm `eval find ./temp -name .svn` -rf
######################################处理程序执行包名称###################################
if [ $1 -eq 1 ]
then
	export PRODUCT=TD8181_PACK_1;
fi
if [ $1 -eq 2 ]
then
	export PRODUCT=TD3520_PACK_2;
fi
if [ $1 -eq 3 ]
then
	export PRODUCT=TD3520_PACK_3;
fi
if [ $1 -eq 4 ]
then
	export PRODUCT=TD3515_PACK_4;
fi
if [ $1 -eq 5 ]
then
	export PRODUCT=TD3520_PACK_SDKV60_H;
fi
if [ $1 -eq 6 ]
then
	export PRODUCT=TD3515_PACK_SDKV40;
fi
if [ $1 -eq 7 ]
then
	export PRODUCT=TD3520_PACK_SDKV60_F;
fi
if [ $1 -eq 8 ]
then
	export PRODUCT=TD3520_PACK_SDKV60_32;
fi
if [ $1 -eq 9 ]
then
	export PRODUCT=TD3520_PACK_SDKV60_HDMI;
fi
if [ $1 -eq 10 ]
then
	export PRODUCT=TDFH_PACK_10;
fi
if [ $1 -eq 11 ]
then
	export PRODUCT=TDNXP_PACK_11;
fi
if [ $1 -eq 12 ]
then
	export PRODUCT=TD3531_PACK_12;
fi
if [ $1 -eq 13 ]
then
	export PRODUCT=TD3520_PACK_960H;
fi

if [ $1 -eq 14 ]
then
	export PRODUCT=TD3531_PACK_SDI;
fi

if [ $1 -eq 15 ]
then
	export PRODUCT=TD3521_PACK_15;
fi

if [ $1 -eq 16 ]
then
	export PRODUCT=TD3520A_PACK_16;
fi

if [ $1 -eq 17 ]
then
	export PRODUCT=TDTIDM8107_PACK_17;
fi

if [ $1 -eq 18 ]
then
	export PRODUCT=TD3531_PACK_12;
fi

if [ $1 -eq 19 ]
then
	export PRODUCT=TD3531_PACK_SDI;
fi

if [ $1 -eq 20 ]
then
	export PRODUCT=TD3531_PACK_20;
fi

if [ $1 -eq 21 ]
then
	export PRODUCT=TD3520A_PACK_21;
fi

if [ $1 -eq 22 ]
then
	export PRODUCT=TD3520D_PACK_22;
fi

#3531 09X版本用的打包PACK ID 任然为20
if [ $1 -eq 23 ]
then
	export PRODUCT=TD3531_PACK_20;
fi

if [ $1 -eq 24 ]
then
	export PRODUCT=TD3521_PACK_24;
fi

if [ $1 -eq 25 ]
then
	export PRODUCT=TD3535_PACK_25;
fi

if [ $1 -eq 26 ]
then
	export PRODUCT=TD3531_PACK_SDI_0BX;
fi

if [ $1 -eq 27 ]
then
	export PRODUCT=TDGM8210_PACK_27;
fi

if [ $1 -eq 28 ]
then
        export PRODUCT=TDGM8283_PACK_28;
fi

if [ $1 -eq 29 ]
then
	export PRODUCT=TD3520D_PACK_22_040;
fi

#############
if [ $2 -eq 1 ]
then
	export COLOR=BLACK;
fi
if [ $2 -eq 2 ]
then
	export COLOR=GREEN;
fi
if [ $2 -eq 3 ]
then
	export COLOR=BLUE;
fi
if [ $2 -eq 4 ]
then
	export COLOR=BLACK;
fi
if [ $2 -eq 5 ]
then
	export COLOR=LBLUE;
fi
if [ $2 -eq 6 ]
then
	export COLOR=GRAY;
fi
if [ $2 -eq 7 ]
then
	export COLOR=BLACK;
fi
if [ $2 -eq 8 ]
then
	export COLOR=RED;
fi
if [ $2 -eq 9 ]
then
	export COLOR=LGREEN;
fi
#############
if [ $3 -eq 1 ]
then
	export UI=TOOL_BUTTON;
fi
if [ $3 -eq 2 ]
then
	export UI=MENU_BUTTON;
fi
if [ $3 -eq 3 ]
then
	export UI=TOOL_ANCHOR;
fi
if [ $3 -eq 4 ]
then
	export UI=MENU_ANCHOR;
fi
#############
if [ $4 -eq 1 ]
then
	export CUSTOM=IN;
fi
if [ $4 -eq 2 ]
then
	export CUSTOM=CN;
fi
if [ $4 -eq 3 ]
then
	export CUSTOM=SP;
fi
if [ $4 -eq 4 ]
then
	export CUSTOM=US02;
fi
if [ $4 -eq 5 ]
then
	export CUSTOM=RU04;
fi
if [ $4 -eq 6 ]
then
	export CUSTOM=BR27;
fi
if [ $4 -eq 7 ]
then
	export CUSTOM=TW01;
fi
if [ $4 -eq 8 ]
then
	export CUSTOM=GB14;
fi
if [ $4 -eq 9 ]
then
	export CUSTOM=IN23;
fi
if [ $4 -eq 10 ]
then
	export CUSTOM=US47;
fi
if [ $4 -eq 11 ]
then
	export CUSTOM=IN25;
fi
if [ $4 -eq 12 ]
then
	export CUSTOM=PL14;
fi
if [ $4 -eq 13 ]
then
	export CUSTOM=TW01_TS;
fi
if [ $4 -eq 14 ]
then
	export CUSTOM=IL03;
fi
if [ $4 -eq 15 ]
then
	export CUSTOM=LV01;
fi
if [ $4 -eq 16 ]
then
	export CUSTOM=SHANGHAI;
fi
if [ $4 -eq 17 ]
then
	export CUSTOM=CBC;
fi
if [ $4 -eq 18 ]
then
	export CUSTOM=GB31;
fi

if [ $4 -eq 20 ]
then
	export CUSTOM=HXHT;
fi

if [ $4 -eq 21 ]
then
	export CUSTOM=YUANZHENG;
fi

if [ $4 -eq 22 ]
then
	export CUSTOM=US02_JP;
fi

if [ $4 -eq 23 ]
then
	export CUSTOM=CN
fi

if [ $4 -eq 24 ]
then
	export CUSTOM=CN_HRSST;
fi


if [ $4 -eq 25 ]
then
	export CUSTOM=TW01_RILI;
fi

if [ $4 -eq 26 ]
then
	export CUSTOM=CN_GB28181
fi

if [ $4 -eq 27 ]
then
	export CUSTOM=ZNV
fi


if [ $4 -eq 28 ]
then
	export CUSTOM=ZNV_CN
fi


if [ $4 -eq 29 ]
then
	export CUSTOM=ZNV_CN_SC
fi

if [ $4 -eq 30 ]
then
	export CUSTOM=ZNV_IN_WNRL
fi

if [ $4 -eq 31 ]
then
	export CUSTOM=CNB_IN
fi

if [ $4 -eq 32 ]
then
	export CUSTOM=KOREAN_IN
fi

if [ $4 -eq 33 ]
then
	export CUSTOM=KR24_CN_JP
fi

if [ $4 -eq 34 ]
then
	export CUSTOM=KR24_IN
fi

if [ $4 -eq 35 ]
then
	export CUSTOM=AP_AU27
fi


#############
if [ $5 -eq 1 ]
then
	export COMPLIE=D;
fi
if [ $5 -eq 2 ]
then
	export COMPLIE=TC;
fi
if [ $5 -eq 3 ]
then
	export COMPLIE=TB;
fi
if [ $5 -eq 4 ]
then
	export COMPLIE=TP;
fi
if [ $5 -eq 5 ]
then
	export COMPLIE=TU;
fi
if [ $5 -eq 6 ]
then
	export COMPLIE=C;
fi
if [ $5 -eq 7 ]
then
	export COMPLIE=B;
fi
if [ $5 -eq 8 ]
then
	export COMPLIE=P;
fi
if [ $5 -eq 9 ]
then
	export COMPLIE=U;
fi



######################################处理程序执行包部分###################################
if [ $1 -eq 1 ]
then
echo "pack XDVR 3.0 firmware with 8181 ..."
cp ./product/modules_8181/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf
cp ./product/dep2.sh.8181 ./temp/dep2.sh
cp ./product/tool_8181/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe/.svn/ -rf && rm ./temp/pppoe/ppp/.svn/ -rf
cp ./product/td8181 ./temp/td8181
./upx ./temp/td8181
cp ./product/gmdvr_mem.cfg.8181 ./temp/gmdvr_mem.cfg
cp ./project/lib/libtd8181.so ./temp/
arm-linux-objdump -D ./temp/td8181 > td8181.d
arm-linux-strip ./temp/td8181
arm-linux-strip ./temp/productcheck
cp ./product/XDVRStart.8181 ./temp/
fi

if [ $1 -eq 2 ]
then
echo "pack XDVR 3.0 firmware with 3520 CIF ..."
cp ./product/modules_3520_cif/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf
cp ./product/dep2.sh.3520.cif ./temp/dep2.sh
cp ./product/tool_3520/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3520 ./temp/td3520
cp ./project/lib/libhi3520.so ./temp/
arm-hismall-linux-objdump -D ./temp/td3520 > td3520_cif.d
arm-hismall-linux-strip ./temp/td3520
#./upx ./temp/td3520 加壳的程序，在执行时，需要内存，所以在内存比较小的机器，不能加壳。2316ME机器的内存比较小。
arm-hismall-linux-strip ./temp/productcheck
cp ./product/XDVRStart.hisi ./temp/
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp
fi

if [ $1 -eq 3 ]
then
echo "pack XDVR 3.0 firmware with 3520 D1..."
cp ./product/modules_3520_d1/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3520.d1 ./temp/dep2.sh
cp ./product/tool_3520/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3520 ./temp/td3520
cp ./project/lib/libhi3520.so ./temp/
arm-hismall-linux-objdump -D ./temp/td3520 > td3520_d1.d
arm-hismall-linux-strip ./temp/td3520
./upx ./temp/td3520
arm-hismall-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp
fi

if [ $1 -eq 4 ]
then
#3515比3520多一个__COMPRESS_UI_FONT__，原因 ：
#如果定义了这个宏，表示ui中的图片采用压缩方式，把ui中的*.bmp 和 font.dat，压缩到ui.tar
#使用时，先把ui.tar解压到/nfsdir（这个是内存）,然后再从/nfsdir中加载图片。
#这样的目的是为了节约flash空间。上述做法，只有td3515上有。3520的flash空间比较，故不采用上述方法。

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -czvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/

echo "pack XDVR 3.0 firmware with 3515..."
cp ./product/modules_3515_cif/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3515 ./temp/dep2.sh
cp ./product/tool_3520/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3515 ./temp/td3515
cp ./project/lib/libhi3515.so ./temp/
arm-hismall-linux-objdump -D ./temp/td3515 > td3515.d
arm-hismall-linux-strip ./temp/td3515
./upx ./temp/td3515
arm-hismall-linux-strip ./temp/productcheck
cp ./product/XDVRStart.hisi ./temp/
cp ./product/product/product.def_TD2308ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def


#压缩客户端的language
cd ./temp/WebServer/language/
tar -zvcf ../language.tar.gz *
cd ../../..
rm ./temp/WebServer/language/ -rf

#压缩DVR端的language
cd ./temp/language/
tar -czvf ../language.tar *
cd ../..
rm ./temp/language -rf

#3515芯片的产品删除：cd的刻录软件
#rm -rf ./temp/mkisofs
rm -rf ./temp/cdrecord
#./upx ./temp/mkisofs

#3515 去掉1路客户端
rm ./temp/WebServer/VideoView.cab

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so

#压缩script
#cd ./temp/WebServer/script/
#tar -zvcf script.tar.gz *
#mv script.tar.gz ../
#rm * -rf
#mv ../script.tar.gz ./
#cd ../../..

#压缩modules
cd ./temp/modules/
tar -zcvf modules.tar.gz *
mv modules.tar.gz ../
rm * -rf
mv ../modules.tar.gz ./
cd ../..


fi

if [ $1 -eq 5 ]
then
echo "pack XDVR 3.0 firmware with 3520 HDHE..."
cp ./product/modules_3520_fd/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3520.d1.fd ./temp/dep2.sh
cp ./product/tool_3520/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3520 ./temp/td3520
cp ./project/lib/libhi3520.so ./temp/
arm-hismall-linux-objdump -D ./temp/td3520 > td3520_d1.d
arm-hismall-linux-strip ./temp/td3520
./upx ./temp/td3520
arm-hismall-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp


fi

if [ $1 -eq 6 ]
then
#3515比3520多一个__COMPRESS_UI_FONT__，原因 ：
#如果定义了这个宏，表示ui中的图片采用压缩方式，把ui中的*.bmp 和 font.dat，压缩到ui.tar
#使用时，先把ui.tar解压到/nfsdir（这个是内存）,然后再从/nfsdir中加载图片。
#这样的目的是为了节约flash空间。上述做法，只有td3515上有。3520的flash空间比较，故不采用上述方法。

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -czvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/

echo "pack XDVR 3.0 firmware with 3515..."
cp ./product/modules_3515_cif_v40/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3515 ./temp/dep2.sh
cp ./product/tool_3520/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3515 ./temp/td3515
cp ./project/lib/libhi3515.so ./temp/
arm-hismall-linux-objdump -D ./temp/td3515 > td3515.d
arm-hismall-linux-strip ./temp/td3515
./upx ./temp/td3515
arm-hismall-linux-strip ./temp/productcheck
cp ./product/XDVRStart.hisi ./temp/
cp ./product/product/product.def_TD2308ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def


#压缩客户端language
cd ./temp/WebServer/language/
tar -zvcf ../language.tar.gz *
cd ../../..
rm ./temp/WebServer/language/ -rf

#压缩DVR端的language
cd ./temp/language/
tar -czvf ../language.tar *
cd ../..
rm ./temp/language -rf

#3515芯片的产品删除：cd的刻录软件
#rm -rf ./temp/mkisofs
rm -rf ./temp/cdrecord
#./upx ./temp/mkisofs

#3515 去掉1路客户端
rm ./temp/WebServer/VideoView.cab

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so



#压缩script
#cd ./temp/WebServer/script/
#tar -zvcf script.tar.gz *
#mv script.tar.gz ../
#rm * -rf
#mv ../script.tar.gz ./
#cd ../../..

#压缩modules
cd ./temp/modules/
tar -zcvf modules.tar.gz *
mv modules.tar.gz ../
rm * -rf
mv ../modules.tar.gz ./
cd ../..
fi


if [ $1 -eq 7 ]
then
echo "pack XDVR 3.0 firmware with 3520 FD..."
cp ./product/modules_3520_fd/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3520.d1.fd ./temp/dep2.sh
cp ./product/tool_3520/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3520 ./temp/td3520
cp ./project/lib/libhi3520.so ./temp/
arm-hismall-linux-objdump -D ./temp/td3520 > td3520_d1.d
arm-hismall-linux-strip ./temp/td3520
#./upx ./temp/td3520 加壳的程序，在执行时，需要内存，所以在内存比较小的机器，不能加壳。2316ME机器的内存比较小。
arm-hismall-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp


fi


if [ $1 -eq 8 ]
then
echo "pack XDVR 3.0 firmware with 3520 2432MD..."


cp ./product/modules_3520_32/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3520.d1.32 ./temp/dep2.sh
cp ./product/tool_3520/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3520 ./temp/td3520
cp ./project/lib/libhi3520.so ./temp/
arm-hismall-linux-objdump -D ./temp/td3520 > td3520_d1.d
arm-hismall-linux-strip ./temp/td3520
./upx ./temp/td3520
arm-hismall-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp
fi


if [ $1 -eq 9 ]
then
echo "pack XDVR 3.0 firmware with 3520 2704HDMI..."
cp ./product/modules_3520_hdmi/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3520.d1.hdmi ./temp/dep2.sh
cp ./product/tool_3520/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3520 ./temp/td3520
cp ./project/lib/libhi3520.so ./temp/
arm-hismall-linux-objdump -D ./temp/td3520 > td3520_d1.d
arm-hismall-linux-strip ./temp/td3520
./upx ./temp/td3520
arm-hismall-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

fi



if [ $1 -eq 10 ]
then

echo "pack XDVR 3.0 firmware with fh..."

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -czvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/

rm ./temp/boot.sh
cp ./product/boot.sh.fh  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_fh/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.fh ./temp/dep2.sh
cp ./product/tool_fh/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/tdfh ./temp/tdfh
cp ./project/lib/libfh36.so ./temp/
#arm-none-linux-gnueabi-objdump -D ./temp/tdfh > tdfh_d1.d
arm-none-linux-gnueabi-strip ./temp/tdfh
./upx_fh ./temp/tdfh
arm-none-linux-gnueabi-strip ./temp/productcheck
#cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.fh ./temp/


#压缩客户端的language
cd ./temp/WebServer/language/
tar -zvcf ../language.tar.gz *
cd ../../..
rm ./temp/WebServer/language/ -rf

#压缩DVR端的language
cd ./temp/language/
tar -czvf ../language.tar *
cd ../..
rm ./temp/language -rf

#fh TD_2316ME_A芯片的产品删除：cd的刻录软件
rm -rf ./temp/dvd+rw-format
rm -rf ./temp/growisofs
rm -rf ./temp/mkisofs
rm -rf ./temp/cdrecord

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so

#压缩modules
cd ./temp/modules/
tar -zcvf modules.tar.gz *
mv modules.tar.gz ../
rm * -rf
mv ../modules.tar.gz ./
cd ../..

fi



if [ $1 -eq 11 ]
then
echo "pack XDVR 3.0 firmware with nxp..."
rm ./temp/boot.sh
cp ./product/boot.sh.nxp  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_nxp/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.nxp ./temp/dep2.sh
cp ./product/tool_nxp/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/tdnxp ./temp/tdnxp
cp ./project/lib/libexNxpSdkLib.so ./temp/
arm-linux-strip ./temp/tdfh
./upx_fh ./temp/tdnxp
arm-linux-strip ./temp/productcheck
cp ./product/XDVRStart.nxp ./temp/
fi

if [ $1 -eq 12 ]
then
echo "pack XDVR 3.0 firmware with 3531 FD..."
rm ./temp/boot.sh
cp ./product/boot.sh.3531SDI  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3531SDI/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3531SDI ./temp/dep2.sh
cp ./product/tool_3531SDI/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3531 ./temp/td3531
cp ./project/lib/libhi3531.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3531 > td3531_d1.d
#arm-hisiv100nptl-linux-strip ./temp/td3531
#./upx_fh ./temp/td3531
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp
fi


if [ $1 -eq 13 ]
then
echo "pack XDVR 3.0 firmware with 3520 26XXLD_S..."

cp ./product/modules_3520_960H/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3520.960H ./temp/dep2.sh
cp ./product/tool_3520/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3520 ./temp/td3520
cp ./project/lib/libhi3520.so ./temp/
arm-hismall-linux-objdump -D ./temp/td3520 > td3520_960H.d
arm-hismall-linux-strip ./temp/td3520
./upx ./temp/td3520
arm-hismall-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp
fi

if [ $1 -eq 14 ]
then
echo "pack XDVR 3.0 firmware with 3531 SDI..."
rm ./temp/boot.sh
cp ./product/boot.sh.3531SDI  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3531SDI/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3531SDI ./temp/dep2.sh
cp ./product/tool_3531SDI/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3531 ./temp/td3531
cp ./project/lib/libhi3531.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3531 > td3531_d1.d
arm-hisiv100nptl-linux-strip ./temp/td3531
#./upx_fh ./temp/td3531
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp
fi

if [ $1 -eq 15 ]
then
echo "pack XDVR 3.0 firmware with 3521 D1..."

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -cvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/
cd temp/ui/
../../lzma ui.tar
cd ../../

	if [ $5 -eq 9 ]
	then
		mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
		cd ./temp/plugin/
		tar -vcf ../plugin.tar *
		cd ../
		../lzma plugin.tar
		rm -rf plugin
		cd ../
	fi
	
rm ./temp/boot.sh
cp ./product/boot.sh.3521  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3521/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3521 ./temp/dep2.sh
cp ./product/tool_3521/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3521 ./temp/td3521
cp ./project/lib/libhi3521.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3521 > td3521_d1.d
arm-hisiv100nptl-linux-strip ./temp/td3521
./upx_fh ./temp/td3521
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

if [ ${13} -eq 1 ]
then
	cp ./product/debug.3521 ./temp/debug.sh
fi

#压缩客户端的language
cd ./temp/WebServer/language/
tar -zvcf ../language.tar.gz *
cd ../../..
rm ./temp/WebServer/language/ -rf


#压缩DVR端的language
cd ./temp/language/
tar -cvf ../language.tar *
cd ../..
cd temp
../lzma language.tar
cd ..
rm ./temp/language -rf

#3520A没有刻录功能
#rm -rf ./temp/dvd+rw-format
#rm -rf ./temp/growisofs
#rm -rf ./temp/mkisofs
cd ./temp/
../lzma mkisofs
../lzma growisofs
cd ../
rm -rf ./temp/cdrecord
rm -rf ./temp/dhcpcd

#flash文件不足，去掉塞班和WindowsMobile的客户端插件
rm ./temp/WebServer/SCam_3rd.SIS
rm ./temp/WebServer/WindowsMobile.CAB

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so

#压缩modules,zxx修改
cd ./temp/modules/
tar -cvf ../modules.tar *
cd ../..
cd temp
../lzma modules.tar
cd ..
rm ./temp/modules/ -rf

cd ./temp/
../lzma libhi3521.so
cd ..

#压缩code_table.dat
cd ./temp/ui/
../../lzma code_table.dat
rm ./temp/ui/code_table.dat -rf
cd ../../

fi

if [ $1 -eq 16 ]
then
echo "pack XDVR 3.0 firmware with 3520A ..."

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -cvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/
cd temp/ui/
../../lzma ui.tar
cd ../../

	if [ $5 -eq 9 ]
	then
		mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
		cd ./temp/plugin/
		tar -vcf ../plugin.tar *
		cd ../
		../lzma plugin.tar
		rm -rf plugin
		cd ../
	fi

rm ./temp/boot.sh
cp ./product/boot.sh.3520A  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3520A/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3520A ./temp/dep2.sh
cp ./product/tool_3520A/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3520a ./temp/td3520a
cp ./project/lib/libhi3520a.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3520a > td3520a_d1.d
arm-hisiv100nptl-linux-strip ./temp/td3520a
./upx_fh ./temp/td3520a
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#mkimg.rootfs temp ./ a_pp yaffs2
#mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

if [ ${13} -eq 1 ]
then
	cp ./product/debug.3520a ./temp/debug.sh
fi

#压缩客户端的language
cd ./temp/WebServer/language/
tar -zvcf ../language.tar.gz *
cd ../../..
rm ./temp/WebServer/language/ -rf


#压缩DVR端的language
cd ./temp/language/
tar -cvf ../language.tar *
cd ../..
cd temp
../lzma language.tar
cd ..
rm ./temp/language -rf

#3520A没有刻录功能
#rm -rf ./temp/dvd+rw-format
#rm -rf ./temp/growisofs
#rm -rf ./temp/mkisofs
rm -rf ./temp/cdrecord
rm -rf ./temp/dhcpcd

cd ./temp/
../lzma mkisofs
../lzma growisofs
cd ../

#flash文件不足，去掉塞班和WindowsMobile的客户端插件
rm ./temp/WebServer/SCam_3rd.SIS
rm ./temp/WebServer/WindowsMobile.CAB

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so

#压缩modules,zxx修改
cd ./temp/modules/
tar -cvf ../modules.tar *
cd ../..
cd temp
../lzma modules.tar
cd ..
rm ./temp/modules/ -rf

cd ./temp/
../lzma libhi3520a.so
cd ..

fi

if [ $1 -eq 17 ]
then
echo "pack XDVR 3.0 firmware with TI DM8107 ..."

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -cvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/
cd temp/ui/
../../lzma ui.tar
cd ../../

rm ./temp/boot.sh
cp ./product/boot.sh.tidm8107  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_tidm8107/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.tidm8107 ./temp/dep2.sh
cp ./product/tool_tidm8107/* ./temp/ -rf && rm ./temp/.svn/ -rf
/home/zhl/ti-arm-tool/arm-2009ql/arm-2009q1/bin/arm-none-linux-gnueabi-strip ./product/tidm8107
./upx_fh ./product/tidm8107
cp ./product/tidm8107 ./temp/tidm8107
cp ./project/lib/libdm8107.so ./temp/
cd ./temp/
../lzma libdm8107.so
cd ..
#arm-none-linux-gnueabi-objdump -D ./temp/td3520a > td3520a_d1.d

#./upx_fh ./temp/tidm8107
arm-none-linux-gnueabi-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.ti ./temp/
#mkimg.rootfs temp ./ a_pp yaffs2
#mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

#压缩客户端的language
cd ./temp/WebServer/language/
tar -zvcf ../language.tar.gz *
cd ../../..
rm ./temp/WebServer/language/ -rf

#压缩DVR端的language
cd ./temp/language/
tar -cvf ../language.tar *
cd ../..
cd temp
../lzma language.tar
cd ..
rm ./temp/language -rf

#没有刻录功能
rm -rf ./temp/dvd+rw-format
rm -rf ./temp/growisofs
rm -rf ./temp/mkisofs
rm -rf ./temp/cdrecord
rm -rf ./temp/dhcpcd

#flash文件不足，去掉塞班和WindowsMobile的客户端插件
rm ./temp/WebServer/SCam_3rd.SIS
rm ./temp/WebServer/WindowsMobile.CAB

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so

rm ./temp/WebServer/VideoView.cab
#rm ./temp/WebServer/WebClientPlugin.pkg
#压缩modules
cd ./temp/modules/
tar -zcvf modules.tar.gz *
mv modules.tar.gz ../
rm * -rf
mv ../modules.tar.gz ./
cd ../..
fi

if [ $1 -eq 18 ]
then
echo "pack XDVR 3.0 firmware with 3531 D1960H 09X..."

	if [ $5 -eq 9 ]
	then
		mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
	fi
rm ./temp/boot.sh
cp ./product/boot.sh.3531_90X  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3531_09X/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3531_90X ./temp/dep2.sh
cp ./product/tool_3531SDI/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3531 ./temp/td3531
cp ./project/lib/libhi3531.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3531 > td3531_d1.d
#arm-hisiv100nptl-linux-strip ./temp/td3531
#./upx_fh ./temp/td3531
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#mkimg.rootfs temp ./ a_pp yaffs2
#mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

	if [ ${13} -eq 1 ]
	then
		cp ./product/debug.3531 ./temp/debug.sh
	fi

fi

if [ $1 -eq 19 ]
then
echo "pack XDVR 3.0 firmware with 3531 SDI 09X..."
rm ./temp/boot.sh
cp ./product/boot.sh.3531_90X  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3531_09X/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3531_90X ./temp/dep2.sh
cp ./product/tool_3531SDI/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3531 ./temp/td3531
cp ./project/lib/libhi3531.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3531 > td3531_d1.d
arm-hisiv100nptl-linux-strip ./temp/td3531
#./upx_fh ./temp/td3531
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#mkimg.rootfs temp ./ a_pp yaffs2
#mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp
	if [ ${13} -eq 1 ]
	then
		cp ./product/debug.3531 ./temp/debug.sh
	fi
fi

if [ $1 -eq 20 ]
then
echo "pack XDVR 3.0 firmware with 3531 28XXND..."

#NVR路暂时去掉苹果客户端
#rm ./temp/WebServer/WebClientPlugin.pkg

mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
cp ./product/modules_3531_N/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf && rm ./temp/modules/.svn/ -rf 
cp ./product/boot.sh.3531_N ./temp/boot.sh
cp ./product/dep2.sh.3531_N ./temp/dep2.sh
cp ./product/eth_restart.sh.3531_N ./temp/eth_restart.sh
cp ./product/tool_3531_N/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3531 ./temp/td3531
cp ./project/lib/libhi3531.so ./temp/
#arm-hisiv100-linux-objdump -D ./temp/td3531 > td3531_d1.d
arm-hisiv100-linux-strip ./temp/td3531
./upx_fh ./temp/td3531
arm-hisiv100-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#./bin/mkyaffs2image temp rootfs_app_prog.yaffs2 1 1
#./bin/mkimage -A arm -T filesystem -C none -n hirootfs -d rootfs_app_prog.yaffs2  appsf31

if [ ${13} -eq 1 ]
then
	cp ./product/debug.3531 ./temp/debug.sh
fi
fi


if [ $1 -eq 21 ]
then
echo "pack XDVR 3.0 firmware with 3520A ..."

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -cvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/
cd temp/ui/
../../lzma ui.tar
cd ../../

mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
rm ./temp/boot.sh
cp ./product/boot.sh.3520A_N  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3520A_N/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3520A_N ./temp/dep2.sh
cp ./product/tool_3520A_N/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3520a ./temp/td3520a
cp ./project/lib/libhi3520a.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3520a > td3520a_d1.d
arm-hisiv100nptl-linux-strip ./temp/td3520a
./upx_fh ./temp/td3520a
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#mkimg.rootfs temp ./ a_pp yaffs2
#mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

if [ ${13} -eq 1 ]
then
	cp ./product/debug.3520a ./temp/debug.sh
fi


#压缩客户端的language
cd ./temp/WebServer/language/
tar -zvcf ../language.tar.gz *
cd ../../..
rm ./temp/WebServer/language/ -rf

#压缩DVR端的language
cd ./temp/language/
tar -czvf ../language.tar *
cd ../..
rm ./temp/language -rf

#3520A没有刻录功能
#rm -rf ./temp/dvd+rw-format
#rm -rf ./temp/growisofs
#rm -rf ./temp/mkisofs
rm -rf ./temp/cdrecord
rm -rf ./temp/dhcpcd

#flash文件不足，去掉塞班和WindowsMobile的客户端插件
rm ./temp/WebServer/SCam_3rd.SIS
rm ./temp/WebServer/WindowsMobile.CAB

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so

#压缩modules
cd ./temp/modules/
tar -zcvf modules.tar.gz *
mv modules.tar.gz ../
rm * -rf
mv ../modules.tar.gz ./
cd ../..
fi

if [ $1 -eq 22 ]
then
echo "pack XDVR 3.0 firmware with 3520D ..."

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -cvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/
cd temp/ui/
../../lzma ui.tar
cd ../../

#mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
	if [ $5 -eq 9 ]
	then
		mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
		cd ./temp/plugin/
		tar -vcf ../plugin.tar *
		cd ../
		../lzma plugin.tar
		rm -rf plugin
		cd ../
	fi
rm ./temp/boot.sh
cp ./product/boot.sh.3520D  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3520D/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
if [ $5 -eq 9 ]
then
	rm -rf ./temp/modules
	cp ./product/modules_3520D_040/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
fi

cp ./product/dep2.sh.3520D ./temp/dep2.sh
cp ./product/tool_3520D/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3520d ./temp/td3520d
arm-hisiv100nptl-linux-strip ./temp/td3520d
./upx_fh ./temp/td3520d

cp ./project/lib/libhi3520d.so ./temp/
if [ $5 -eq 9 ]
then
	rm -rf ./temp/libhi3520d.so
	cp ./product/lib_3520D_040/libhi3520d.so ./temp/
fi
#arm-hisiv100nptl-linux-objdump -D ./temp/td3520a > td3520a_d1.d
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#mkimg.rootfs temp ./ a_pp yaffs2
#mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

if [ ${13} -eq 1 ]
then
	cp ./product/debug.3520d ./temp/debug.sh
fi

#压缩客户端的language
cd ./temp/WebServer/language/
tar -zvcf ../language.tar.gz *
cd ../../..
rm ./temp/WebServer/language/ -rf

#压缩DVR端的language
cd ./temp/language/
tar -cvf ../language.tar *
cd ../..
cd temp
../lzma language.tar
cd ..
rm ./temp/language -rf

#3520A没有刻录功能
#rm -rf ./temp/dvd+rw-format
#rm -rf ./temp/growisofs
#rm -rf ./temp/mkisofs
rm -rf ./temp/cdrecord
rm -rf ./temp/dhcpcd

cd ./temp/
../lzma mkisofs
../lzma growisofs
cd ../

#flash文件不足，去掉塞班和WindowsMobile的客户端插件
rm ./temp/WebServer/SCam_3rd.SIS
rm ./temp/WebServer/WindowsMobile.CAB

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so

#压缩modules,zxx修改
cd ./temp/modules/
tar -cvf ../modules.tar *
cd ../..
cd temp
../lzma modules.tar
cd ..
rm ./temp/modules/ -rf

cd ./temp/
../lzma libhi3520d.so
cd ..

fi

if [ $1 -eq 23 ]
then
echo "pack XDVR 3.0 firmware with 3531 NVR 09x..."

#NVR路暂时去掉苹果客户端
#rm ./temp/WebServer/WebClientPlugin.pkg

mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
cp ./product/modules_3531_09x_N/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf && rm ./temp/modules/.svn/ -rf 
cp ./product/boot.sh.3531_09x_N ./temp/boot.sh
cp ./product/dep2.sh.3531_09x_N ./temp/dep2.sh
cp ./product/eth_restart.sh.3531.09x_N ./temp/eth_restart.sh
cp ./product/tool_3531_09x_N/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3531 ./temp/td3531
cp ./project/lib/libhi3531.so ./temp/
#arm-hisiv100-linux-objdump -D ./temp/td3531 > td3531_d1.d
arm-hisiv100-linux-strip ./temp/td3531
./upx_fh ./temp/td3531
arm-hisiv100-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#./bin/mkyaffs2image temp rootfs_app_prog.yaffs2 1 1
#./bin/mkimage -A arm -T filesystem -C none -n hirootfs -d rootfs_app_prog.yaffs2  appsf31
if [ ${13} -eq 1 ]
then
	cp ./product/debug.3531 ./temp/debug.sh
fi
fi



if [ $1 -eq 24 ]
then
echo "pack NVR 3.0 firmware with 3521 ..."

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -czvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/

#mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
mkdir ./temp/plugin && cp ./product/plugin/libtsnetdevice.so ./temp/plugin/
rm ./temp/boot.sh
cp ./product/boot.sh.3521  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3521/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3521 ./temp/dep2.sh
cp ./product/tool_3521/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3521 ./temp/td3521
cp ./project/lib/libhi3521.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3521 > td3521_d1.d
arm-hisiv100nptl-linux-strip ./temp/td3521
./upx_fh ./temp/td3521
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#mkimg.rootfs temp ./ a_pp yaffs2
#mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

if [ ${13} -eq 1 ]
then
	cp ./product/debug.3521 ./temp/debug.sh
fi


#压缩客户端的language
cd ./temp/WebServer/language/
tar -zvcf ../language.tar.gz *
cd ../../..
rm ./temp/WebServer/language/ -rf

#压缩DVR端的language
cd ./temp/language/
tar -cvf ../language.tar *
cd ../..
cd temp
../lzma language.tar
cd ..
rm ./temp/language -rf

#3520A没有刻录功能
#rm -rf ./temp/dvd+rw-format
#rm -rf ./temp/growisofs
#rm -rf ./temp/mkisofs
cd ./temp/
tar -zcvf mkisofs.tar.gz mkisofs
rm -rf mkisofs
cd ../
rm -rf ./temp/cdrecord
rm -rf ./temp/dhcpcd

#flash文件不足，去掉塞班和WindowsMobile的客户端插件
rm ./temp/WebServer/SCam_3rd.SIS
rm ./temp/WebServer/WindowsMobile.CAB

#压缩modules,zxx修改
cd ./temp/modules/
tar -cvf ../modules.tar *
cd ../..
cd temp
../lzma modules.tar
cd ..
rm ./temp/modules/ -rf

fi

if [ $1 -eq 25 ]
then
echo "pack NVR 3.0 firmware with 3535 NVR..."

#NVR暂时去掉苹果客户端
#rm ./temp/WebServer/WebClientPlugin.pkg

mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
cp ./product/modules_3535/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf && rm ./temp/modules/.svn/ -rf 
cp ./product/boot.sh.3535 ./temp/boot.sh
cp ./product/dep2.sh.3535 ./temp/dep2.sh
#cp ./product/eth_restart.sh.3535 ./temp/eth_restart.sh
cp ./product/tool_3535/* ./temp/ -rf && rm ./temp/.svn/ -rf && rm ./temp/pppoe -rf && rm ./temp/dhcpcd -rf
cp ./product/td3535 ./temp/td3535
cp ./project/lib/libhi3535.so ./temp/

arm-hisiv100-linux-strip ./temp/td3535
#./upx_fh ./temp/td3535
arm-hisiv100-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#./bin/mkyaffs2image temp rootfs_app_prog.yaffs2 1 1
#./bin/mkimage -A arm -T filesystem -C none -n hirootfs -d rootfs_app_prog.yaffs2  appsf31
if [ ${13} -eq 1 ]
then
	cp ./product/debug.3535 ./temp/debug.sh
fi

fi



if [ $1 -eq 26 ]
then
echo "pack XDVR 3.0 firmware with 3531 0BX SDI..."
rm ./temp/boot.sh

if [ $5 -eq 9 ]
then
	mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
fi
	
cp ./product/boot.sh.3531_0BX  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3531_0BX/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3531_0BX ./temp/dep2.sh
cp ./product/tool_3531_0BX/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3531 ./temp/td3531
cp ./project/lib/libhi3531.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3531 > td3531_d1.d
arm-hisiv100nptl-linux-strip ./temp/td3531
#./upx_fh ./temp/td3531
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
mkimg.rootfs temp ./ a_pp yaffs2
mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp
if [ ${13} -eq 1 ]
then
	cp ./product/debug.3531 ./temp/debug.sh
fi
fi

if [ $1 -eq 27 ]
then
echo "pack XDVR 3.0 firmware with GM8210..."
rm ./temp/boot.sh
cp ./product/boot.sh.GM8210  ./temp/boot.sh && dos2unix ./temp/boot.sh && chmod 777 ./temp/boot.sh
cp ./product/modules_GM8210/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
#cp ./product/language/* ./temp/language/ -rf && rm ./temp/language/.svn/ -rf
cp ./product/dep2.sh.GM8210 ./temp/dep2.sh
cp ./product/tool_GM8210/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/gm8210 ./temp/gm8210
cp ./project/lib/libfa8210.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3531 > td3531_d1.d
arm-unknown-linux-uclibcgnueabi-strip ./temp/gm8210
./upx_fh ./temp/gm8210
#arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#mkimg.rootfs temp ./ a_pp yaffs2
#mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

	if [ $5 -eq 9 ]
	then
                mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
	fi
fi


if [ $1 -eq 28 ]
then
echo "pack XDVR 3.0 firmware with GM8283..."
cp ./product/boot.sh.GM8283 ./temp/boot.sh && dos2unix ./temp/boot.sh && chmod 777 ./temp/boot.sh
cp ./product/dep2.sh.GM8283 ./temp/dep2.sh
cp ./product/tool_GM8283/* ./temp/ -rf && rm ./temp/.svn -rf
cp ./product/lib_GM8283/libfa8283.so ./temp/libfa8283.so
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
cp ./product/language ./temp/language -rf && rm ./temp/language/.svn -rf

cp ./product/gm8283 ./temp/gm8283
arm-unknown-linux-uclibcgnueabi-strip ./temp/gm8283
./upx_fh ./temp/gm8283

cd ./temp/WebServer
tar -czvf language.tar.gz language 
rm -rf language
cd ../..

rm ./temp/modules.tar.lzma
cp ./product/modules_GM8283 ./temp/modules -rf && rm ./temp/modules/.svn -rf && rm ./temp/modules/drv/.svn -rf && rm ./temp/modules/netmount/.svn -rf && rm ./temp/modules/drv/3.3.0/.svn -rf
cd ./temp
tar -cvf modules.tar modules 
lzma modules.tar
rm -rf modules
cd ..

rm ./temp/ui.tar.lzma
cp ./product/ui_1 ./temp/ui -rf && rm ./temp/ui/.svn -rf && rm ./temp/ui/ui_anchor/.svn -rf && rm ./temp/ui/ui_common/.svn -rf && rm ./temp/ui/ui_logo/.svn -rf && rm ./temp/ui/ui_menu/.svn -rf && rm ./temp/ui/ui_normal/.svn -rf && rm ./temp/ui/ui_toolbar/.svn -rf
cd ./temp
tar -cvf ui.tar ui 
lzma ui.tar
rm -rf ui
cd ..

fi

if [ $1 -eq 29 ]
then
echo "pack XDVR 3.0 firmware with 3520D V040 ..."

mv ./temp/ui/color.ini                   ./temp/
mv ./temp/ui/fontlib_cn_s.txt            ./temp/
mv ./temp/ui/icon_logo.bmp               ./temp/
mv ./temp/ui/icon_logo_trans.bmp         ./temp/
mv ./temp/ui/code_table.dat              ./temp/
cd ./temp/ui/ && tar -cvf ../ui.tar *
cd ../../
rm ./temp/ui/* -rf
mv ./temp/color.ini                      ./temp/ui/
mv ./temp/fontlib_cn_s.txt               ./temp/ui/
mv ./temp/icon_logo.bmp                  ./temp/ui/
mv ./temp/icon_logo_trans.bmp            ./temp/ui/
mv ./temp/code_table.dat                 ./temp/ui/
mv ./temp/ui.tar                         ./temp/ui/
cd temp/ui/
../../lzma ui.tar
cd ../../

#mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
	if [ $5 -eq 9 ]
	then
		mkdir ./temp/plugin && cp ./product/plugin/*.so ./temp/plugin/
		cd ./temp/plugin/
		tar -vcf ../plugin.tar *
		cd ../
		../lzma plugin.tar
		rm -rf plugin
		cd ../
	fi
rm ./temp/boot.sh
cp ./product/boot.sh.3520D  ./temp/boot.sh      && dos2unix ./temp/boot.sh    && chmod 777 ./temp/boot.sh
cp ./product/modules_3520D_040/ ./temp/modules/ -rf && rm ./temp/modules/.svn/ -rf && rm ./temp/modules/extdrv/.svn/ -rf && rm ./temp/modules/pppoe/.svn/ -rf && rm ./temp/modules/pci_boot/.svn -rf
cp ./product/dep2.sh.3520D ./temp/dep2.sh
cp ./product/tool_3520D/* ./temp/ -rf && rm ./temp/.svn/ -rf
cp ./product/td3520d ./temp/td3520d
arm-hisiv100nptl-linux-strip ./temp/td3520d
./upx_fh ./temp/td3520d
# xian
#cp ./product/td3520d ./temp/td3520d
cp ./project/lib/libhi3520d.so ./temp/
#arm-hisiv100nptl-linux-objdump -D ./temp/td3520a > td3520a_d1.d
arm-hisiv100nptl-linux-strip ./temp/productcheck
cp ./product/product/product.def_TD2316ME  ./temp/product/product.def && dos2unix ./temp/product/product.def && chmod 777 ./temp/product/product.def
cp ./product/XDVRStart.hisi ./temp/
#mkimg.rootfs temp ./ a_pp yaffs2
#mkimage -A arm -T filesystem -C none -n hirootfs -d ./a_pp.yaffs2 ./a_pp

if [ ${13} -eq 1 ]
then
	cp ./product/debug.3520d ./temp/debug.sh
fi

#压缩客户端的language
cd ./temp/WebServer/language/
	if [ $5 -eq 9 ]
	then
		tar -vcf ../language.tar *
		cd ../
		../../lzma language.tar
		cd ../../
	else
		tar -zvcf ../language.tar.gz *
		cd ../../..
	fi

rm ./temp/WebServer/language/ -rf

#压缩DVR端的language
cd ./temp/language/
tar -cvf ../language.tar *
cd ../..
cd temp
../lzma language.tar
cd ..
rm ./temp/language -rf

#3520A没有刻录功能
#rm -rf ./temp/dvd+rw-format
#rm -rf ./temp/growisofs
#rm -rf ./temp/mkisofs
rm -rf ./temp/cdrecord
rm -rf ./temp/dhcpcd

cd ./temp/
../lzma mkisofs
../lzma growisofs
cd ../

#flash文件不足，去掉塞班和WindowsMobile的客户端插件
rm ./temp/WebServer/SCam_3rd.SIS
rm ./temp/WebServer/WindowsMobile.CAB

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so

#压缩modules,zxx修改
cd ./temp/modules/
tar -cvf ../modules.tar *
cd ../..
cd temp
../lzma modules.tar
cd ..
rm ./temp/modules/ -rf

cd ./temp/
../lzma libhi3520d.so
cd ..

fi

#第一套客户端界面
if [ $6 -eq 1 ]
then
	echo "1111111111"
	
	rm  ./temp/WebServer/WebClient_*.html -rf
	
	rm  ./temp/WebServer/css_style_*      -rf
	
	rm  ./temp/WebServer/res_*            -rf
	
	rm  ./temp/WebServer/WebClientPlugin_*.pkg  -rf
	
	export IEMODE=IE1;
fi


#第二套客户端界面
if [ $6 -eq 2 ]
then
	echo "22222222"
	rm  ./temp/WebServer/WebClient.html      -rf
	mv  ./temp/WebServer/WebClient_dark.html ./temp/WebServer/WebClient.html
	rm  ./temp/WebServer/WebClient_*.html -rf
	
	
	rm  ./temp/WebServer/css_style           -rf
	mv  ./temp/WebServer/css_style_dark      ./temp/WebServer/css_style
	rm  ./temp/WebServer/css_style_*      -rf
	

	rm  ./temp/WebServer/res                 -rf
	mv  ./temp/WebServer/res_dark            ./temp/WebServer/res
	rm  ./temp/WebServer/res_*            -rf	

	#rm  ./temp/WebServer/WebClientPlugin.pkg  -rf
	#mv  ./temp/WebServer/WebClientPlugin_dark.pkg  ./temp/WebServer/WebClientPlugin.pkg  
	rm  ./temp/WebServer/WebClientPlugin_*.pkg  -rf
	

	cd ./temp/WebServer/script
	ChangeInterface 0x06 0x1D 0x51 1
	cd ../../..
	
	export IEMODE=IE2;
fi



#第三套客户端界面
if [ $6 -eq 3 ]
then
	echo "3333333"
	rm  ./temp/WebServer/WebClient.html      -rf
	mv  ./temp/WebServer/WebClient_red.html ./temp/WebServer/WebClient.html
	rm  ./temp/WebServer/WebClient_*.html -rf
	
	rm  ./temp/WebServer/css_style           -rf
	mv  ./temp/WebServer/css_style_red      ./temp/WebServer/css_style
	rm  ./temp/WebServer/css_style_*      -rf

	rm  ./temp/WebServer/res                 -rf
	mv  ./temp/WebServer/res_red            ./temp/WebServer/res
	rm  ./temp/WebServer/res_*            -rf	

	#rm  ./temp/WebServer/WebClientPlugin.pkg  -rf
	#mv  ./temp/WebServer/WebClientPlugin_red.pkg  ./temp/WebServer/WebClientPlugin.pkg  
	rm  ./temp/WebServer/WebClientPlugin_*.pkg  -rf
	
	cd ./temp/WebServer/script
	ChangeInterface 0xCA 0x00 0x16 2
	cd ../../..
	
	export IEMODE=IE3;
fi

#cd ./temp/WebServer/script/
if [ $4 -eq 14 ] ; then
#IL03中加入希伯来
	echo "IL03 have HEBREW"
else
	if [ $4 -eq 5 ] ; then
		echo "ru04 no HEBREW"
	else
		echo "Delete hebrew"
		DeleteLanguage hebrew
	fi
fi
#cd ../../../

cd ./temp/WebServer/
mkdir script_temp
for f in `ls script`
do
	java -jar ../../yuicompressor.jar ./script/$f -o ./script_temp/$f --charset utf-8
done
rm script -rf
mv script_temp script
cd ../..




#防止还有.svn
rm `eval find ./temp -name .svn` -rf

#删除libtsnetdevice.so
rm -rf ./temp/libtsnetdevice.so



#打包所有


if [ $7 -eq 1 ]
then
	echo "use 3G"
	export HAVE3G=USE_3G_;
fi


if [ $8 -eq 1 ]
then
	echo "have osdtwolines"
	export OSDTWOLINES=OSDLINES_;
fi

if [ $9 -eq 1 ]
then
	echo "have onvif"
	export SUPPORTONVIF=ONVIF_;
else
	echo "no onvif"
	rm ./temp/plugin/libonvifdevice.so
fi

if [ ${10} -eq 1 ]
then
	echo "have nat"
	export SUPPORTNAT=NAT_;
else
	echo "not have nat" ${10}
fi

if [ ${11} -eq 1 ]
then
	echo "have push"
	export SUPPORTPUSH=PUSH_;
else
	echo "not have push" ${11}
fi

if [ ${12} -eq 1 ]
then
	echo "have api"
	export SUPPORTAPI=API_;
else
	echo "not have api" ${12}
fi

if [ ${12} -eq 1 ]
then
	cp ./project/lib/libApiNetSocket.so ./temp/
	cp ./project/lib/libApiServer.so ./temp/
	cp ./project/lib/libApiShareLib.so ./temp/
	cp ./project/lib/libApiuuid.so ./temp/
	if [[ ${1} != 12  &&  ${1} != 14  &&  ${1} != 18  &&  ${1} != 19  &&  ${1} != 20  &&  ${1} != 23  &&  ${1} != 25  &&  ${1} != 26 ]]
	then
		cd ./temp
		../lzma libApiNetSocket.so
		../lzma libApiServer.so
		../lzma libApiShareLib.so
		../lzma libApiuuid.so
		cd ..
	fi
fi

#
rm ./temp/WebServer/OEM -rf
rm ./temp/WebServer/Nat -rf

if [ $5 -eq 9 ]
then
	if [ -f ./temp/WebSites/logo/logo_nvr.png ]; then
		rm ./temp/WebSites/logo/logo.png
		mv ./temp/WebSites/logo/logo_nvr.png ./temp/WebSites/logo/logo.png
	fi
else
	rm ./temp/WebSites/logo/logo_nvr.png
fi


if [[ $1 -eq 15 || $1 -eq 16 || $1 -eq 22 || $1 -eq 18 || $1 -eq 29 ]]
then
	echo "11111111111111111111111111111111111111= ${1}"
	if [ $5 -eq 9 ]
	then
		rm ./temp/WebServer/server.js
		cp ./product/WebSites/server.js.hybird   ./temp/WebServer/server.js
	fi
fi

if [[ $1 -eq 15 || $1 -eq 16 || $1 -eq 22 || $1 -eq 29 ]]
then
	echo "11111111111111111111111111111111111111= ${1}"
	if [ $5 -eq 9 ]
	then
		cd ./temp/WebServer/
		rm VideoView.cab
		tar -vcf ../WebServer.tar *
		cd ../
		../lzma WebServer.tar
		rm -rf WebServer
		cd ../
	fi
fi

cp ./project/lib/libgomp_hisi.so ./temp/libgomp.so.1 -f
if [[ $1 -eq 27 || $1 -eq 28 ]]
then
	echo "11111111111111111111111111111111111111= ${1}"
	cp ./project/lib/libgmp_zhiyuan.so ./temp/libgomp.so.1 -f
fi
#lzma libgmp.so.1
if [[ $1 -eq 15 || $1 -eq 16 || $1 -eq 22 || $1 -eq 24 || $1 -eq 29 ]]
then
	echo "11111111111111111111111111111111111111= ${1}"
	cd ./temp
	../lzma libgomp.so.1
	cd ..
fi

if [ ${13} -eq 1 ]
then
	cp ./product/DVRService ./temp/DVRService
fi

chmod -R 777 ./temp/*
cd ./temp && tar zvcf ../${PRODUCT}_${COLOR}_${UI}_${IEMODE}_${HAVE3G}${OSDTWOLINES}${COMPLIE}_${SUPPORTONVIF}${SUPPORTNAT}${SUPPORTPUSH}${SUPPORTAPI}${CUSTOM}.tar *
cd ../

rm ./temp/preupgrade.sh
rm ./temp/netupgrade.sh
cp ./product/preupgrade_bkc.sh ./temp/preupgrade.sh && dos2unix ./temp/preupgrade.sh && chmod 777 ./temp/preupgrade.sh
cp ./product/netupgrade_bkc.sh ./temp/netupgrade.sh && dos2unix ./temp/netupgrade.sh && chmod 777 ./temp/netupgrade.sh
cd ./temp && tar zvcf ../${PRODUCT}_${COLOR}_${UI}_${IEMODE}_${HAVE3G}${OSDTWOLINES}${COMPLIE}_${SUPPORTONVIF}${SUPPORTNAT}${SUPPORTPUSH}${SUPPORTAPI}${CUSTOM}_BKC.tar *

#cd ../
#rm ./temp -rf

echo "pack complete."
exit 0
