/***********************************************************************
** Copyright (C) Tongwei Video Technology Co.,Ltd. All rights reserved.
** Author       : 
** Date         : 2010-04
** Name         : IDToStringID.h
** Version      : 1.0
** Description  : 把不同的ID转换为相关字符串ID
** Modify Record:
1:
***********************************************************************/

#ifndef ID_TO_STRINGID_H_
#define ID_TO_STRINGID_H_


//日志相关ID
inline unsigned long LogIDToStrID(unsigned long logID)
{
	switch(logID)
	{
		//系统控制(Control)
	case LOG_TYPE_BOOT:
		return E_STR_ID_LOG_BOOT;
	case LOG_TYPE_SHUTDOWN:
		return E_STR_ID_LOG_SHUTDOWN;
	case LOG_TYPE_REBOOT:
		return E_STR_ID_LOG_REBOOT;
	case LOG_TYPE_FORMAT_SUCC:
		return E_STR_ID_LOG_FORMAT_SUCC;
	case LOG_TYPE_FORMAT_FAIL:
		return E_STR_ID_LOG_FORMAT_FAIL;
	case LOG_TYPE_UPGRADE_SUCC:
		return E_STR_ID_LOG_UPGARDE_SUCC;
	case LOG_TYPE_UPGRADE_FAIL:
		return E_STR_ID_LOG_UPGRADE_FAIL;
	case LOG_TYPE_CLEAR_ALARM:
		return E_STR_ID_LOG_CLEAR_ALARM;
	case LOG_TYPE_OPEN_ALARM:
		return E_STR_ID_LOG_OPEN_ALARM;
	case LOG_TYPE_MANUAL_START:
		return E_STR_ID_LOG_MANUAL_START;
	case LOG_TYPE_MANUAL_STOP:
		return E_STR_ID_LOG_MANUAL_STOP;
	case LOG_TYPE_PTZ_ENTER:
		return E_STR_ID_LOG_PTZ_ENTER;
	case LOG_TYPE_PTZ_CTRL:
		return E_STR_ID_LOG_PTZ_CTRL;
	case LOG_TYPE_PTZ_EXIT:
		return E_STR_ID_LOG_PTZ_EXIT;
	case LOG_TYPE_AUDIO_CH_CHANGE:
		return E_STR_ID_LOG_AUDIO_CH_CHAE;
	case LOG_TYPE_VOLUME_ADJUST:
		return E_STR_ID_LOG_VOLUME_ADJUST;
	case LOG_TYPE_MUTE_ENABLE:
		return E_STR_ID_LOG_MUTE_ENABLE;
	case LOG_TYPE_MUTE_DISENABLE:
		return E_STR_ID_LOG_MUTE_DISABLE;
	case LOG_TYPE_DWELL_ENABLE:
		return E_STR_ID_LOG_DWELL_ENABLE;
	case LOG_TYPE_DWELL_DISENABLE:
		return E_STR_ID_LOG_DWELL_DISABLE;
	case LOG_TYPE_LOG_IN:
		return E_STR_ID_LOG_LOG_ON;
	case LOG_TYPE_LOG_OFF:
		return E_STR_ID_LOG_LOG_OFF;
	case LOG_TYPE_CHANGE_TIME:
		return E_STR_ID_LOG_MODIFY_TIME;
	case LOG_TYPE_MANUAL_SNAP_SUCC:
		return E_STR_ID_LOG_MANUAL_SNAP_SUC;
	case LOG_TYPE_MANUAL_SNAP_FAIL:
		return E_STR_ID_LOG_MANUAL_SNAP_FAI;

		//系统配置(basic)
	case LOG_TYPE_CHGE_VIDEO_FORMAT:
		return E_STR_ID_LOG_CHGE_VIDEO_FORMAT;
	case LOG_TYPE_CHGE_VGA_RESOLUTION:
		return E_STR_ID_LOG_CHGE_MONITOR;
	case LOG_TYPE_CHGE_LANGUAGE:
		return E_STR_ID_LOG_CHGE_LANGUAGE;
	case LOG_TYPE_CHGE_NET_USER_NUM:
		return E_STR_ID_LOG_CHGE_NET_USER_NUM;
	case LOG_TYPE_CHGE_TIME_ZONE:
		return E_STR_ID_LOG_CHGE_TIME_ZONE;
	case LOG_TYPE_NTP_MANUAL:
		return E_STR_ID_LOG_MANUAL_SYNC_NTP;
	case LOG_TYPE_NTP_ON:
		return E_STR_ID_LOG_NTP_ON;
	case LOG_TYPE_NTP_OFF:
		return E_STR_ID_LOG_NTP_OFF;
	case LOG_TYPE_CHGE_NTP_SERVER:
		return E_STR_ID_LOG_CHGE_NTP_SERVER;
	case LOG_TYPE_CHGE_DST:
		return E_STR_ID_LOG_CHGE_DST;
	case LOG_TYPE_PASSWD_ON:
		return E_STR_ID_LOG_PASSWORD_ON;
	case LOG_TYPE_PASSWD_OFF:
		return E_STR_ID_LOG_PASSWORD_OFF;
		//系统配置(live)
	case LOG_TYPE_CHGE_CAM_NAME:
		return E_STR_ID_LOG_CHGE_CAM_NAME;
	case LOG_TYPE_MODIFY_COLOR:
		return E_STR_ID_LOG_MODIFY_COLOR;
	case LOG_TYPE_CHGE_HOST_MONITOR:
		return E_STR_ID_LOG_CHGE_HOST_MONITOR;
	case LOG_TYPE_CHGE_SPOT:
		return E_STR_ID_LOG_CHGE_SPOT;
	case LOG_TYPE_CHGE_OSD:
		return E_STR_ID_LOG_CHGE_OSD;
		//系统配置(record)
	case LOG_TYPE_CHGE_LOCAL_ENCODE:
		return E_STR_ID_LOG_CHGE_LOCAL_ENCODE;
	case LOG_TYPE_CHGE_REC_VIDEO_SWITCH:
		return E_STR_ID_LOG_CHGE_REC_VIDEO_SWITCH;
	case LOG_TYPE_CHGE_REC_AUDIO_SWITCH:
		return E_STR_ID_LOG_CHGE_REC_AUDIO_SWITCH;
	case LOG_TYPE_CHGE_REC_REDU_SWITCH:
		return E_STR_ID_LOG_CHGE_REC_REDU_SWITCH;
	case LOG_TYPE_CHGE_REC_PRE_TIME:
		return E_STR_ID_LOG_CHGE_PRE_TIME;
	case LOG_TYPE_CHGE_REC_POST_TIME:
		return E_STR_ID_LOG_CHGE_POST_TIME;
	case LOG_TYPE_CHGE_REC_HOLD_TIME:
		return E_STR_ID_LOG_CHGE_HOLD_TIME;
		//系统配置(schedule)
	case LOG_TYPE_CHGE_SCH_SCHEDULE:
		return E_STR_ID_LOG_CHGE_SCH_SCHEDULE;
	case LOG_TYPE_CHGE_SCH_MOTION:
		return E_STR_ID_LOG_CHGE_SCH_MOTION;
	case LOG_TYPE_CHGE_SCH_ALARM:
		return E_STR_ID_LOG_CHGE_SCH_ALARM;
		//系统配置(sensor)
	case LOG_TYPE_CHGE_SENSOR_SWITCH:
		return E_STR_ID_LOG_CHGE_SENSOR_SWITCH;
	case LOG_TYPE_CHGE_SENSOR_TYPE:
		return E_STR_ID_LOG_CHGE_SENSOR_TYPE;
	case LOG_TYPE_CHGE_SENSOR_TRIGGER:
		return E_STR_ID_LOG_CHGE_SENSOR_TRIGGER;
	case LOG_TYPE_CHGE_SENSOR_SCH:
		return E_STR_ID_LOG_CHGE_SENSOR_SCH;
		//系统配置(motion)
	case LOG_TYPE_CHGE_MOTION_SWITCH:
		return E_STR_ID_LOG_CHGE_MOTION_SWITCH;
	case LOG_TYPE_CHGE_MOTION_SENS:
		return E_STR_ID_LOG_CHGE_MOTION_SENS;
	case LOG_TYPE_CHGE_MOTION_AREA:
		return E_STR_ID_LOG_CHGE_MOTION_AREA;
	case LOG_TYPE_CHGE_MOTION_TRIGGER:
		return E_STR_ID_LOG_CHGE_MOTION_TRIGGER;
	case LOG_TYPE_CHGE_MOTION_SCH:
		return E_STR_ID_LOG_CHGE_MOTION_SCH;
		//系统配置(video loss)
	case LOG_TYPE_CHGE_VL_TRIGGER:
		return E_STR_ID_LOG_CHGE_VL_TRIGGER;
		//系统配置(relay)
	case LOG_TYPE_CHGE_RELAY_SWITCH:
		return E_STR_ID_LOG_CHGE_RELAY_SWITCH;
	case LOG_TYPE_CHGE_RELAY_SCH:
		return E_STR_ID_LOG_CHGE_RELAY_SCH;
		//系统配置(buzzer)
	case LOG_TYPE_BUZZER_ON:
		return E_STR_ID_LOG_BUZZER_ON;
	case LOG_TYPE_BUZZER_OFF:
		return E_STR_ID_LOG_BUZZER_OFF;
	case LOG_TYPE_CHGE_BUZZER_SCH:
		return E_STR_ID_LOG_CHGE_BUZZER_SCH;
		//系统配置(network)
	case LOG_TYPE_CHGE_HTTP_PORT:
		return E_STR_ID_LOG_CHGE_HTTP_PORT;
	case LOG_TYPE_CHGE_SER_PORT:
		return E_STR_ID_LOG_CHGE_SER_PORT;
	case LOG_TYPE_CHGE_IP:
		return E_STR_ID_LOG_CHGE_IP;
	case LOG_TYPE_DHCP_SUCC:
		return E_STR_ID_LOG_CHGE_DHCP_SUCC;
	case LOG_TYPE_DHCP_FAIL:
		return E_STR_ID_LOG_CHGE_DHCP_FAIL;
	case LOG_TYPE_CHGE_PPPOE:
		return E_STR_ID_LOG_CHGE_PPPOE;
	case LOG_TYPE_CHGE_DDNS:
		return E_STR_ID_LOG_CHGE_DDNS;
	case LOG_TYPE_NET_STREAM_CFG:
		return E_STR_ID_LOG_CHGE_NET_ENCODE;
		//系统配置(ptz)
	case LOG_TYPE_CHGE_SERIAL:
		return E_STR_ID_LOG_CHGE_SERIAL;
	case LOG_TYPE_PRESET_MODIFY:
		return E_STR_ID_LOG_MODIFY_PRESET;
	case LOG_TYPE_CRUISE_MODIFY:
		return E_STR_ID_LOG_MODIFY_CRUISE;
	case LOG_TYPE_TRACK_MODIFY:
		return E_STR_ID_LOG_MODIFY_TRACK;
		//系统配置(user)
	case LOG_TYPE_USER_ADD:
		return E_STR_ID_LOG_ADD_USER;
	case LOG_TYPE_USER_MODIFY:
		return E_STR_ID_LOG_MODIFY_USER;
	case LOG_TYPE_USER_DELETE:
		return E_STR_ID_LOG_DELETE_USER;
	case LOG_TYPE_CHANGE_PASSWD:
		return E_STR_ID_LOG_CHGE_PASSWORD;
		//系统配置(op)
	case LOG_TYPE_LOAD_DEFAULT:
		return E_STR_ID_LOG_LOAD_DEFAULT;
	case LOG_TYPE_IMPORT_CONFIG:
		return E_STR_ID_LOG_IMPORT_CONFIG;
	case LOG_TYPE_EXPORT_CONFIG:
		return E_STR_ID_LOG_EXPORT_CONFIG;
        //系统配置(email)
	case LOG_TYPE_CHGE_SEND_EMAIL:
		return E_STR_ID_LOG_CHGE_SEND_EMAIL;
	case LOG_TYPE_CHGE_RECV_EMAIL:
		return E_STR_ID_LOG_CHG_RECV_EMAIL;
	case LOG_TYPE_CHGE_SNAP_SETTING:
		return E_STR_ID_LOG_CHG_SNAP_SETTING;
		//系统配置(IPCamera)
	case LOG_TYPE_IPCAM_ADD:
		return E_STR_ID_LOG_IPCAM_ADD;
	case LOG_TYPE_IPCAM_SETUP:
		return E_STR_ID_LOG_IPCAM_SETUP;
	case LOG_TYPE_IPCAM_DELETE:
		return E_STR_ID_LOG_IPCAM_DELETE;
	case LOG_TYPE_IPCAM_CONNECTED:
		return E_STR_ID_LOG_IPCAM_CONNECTED;
	case LOG_TYPE_IPCAM_DISCONNECTED:
		return E_STR_ID_LOG_IPCAM_DISCONNECTED;
		//录像回放(Playback)
	case LOG_TYPE_PLAYBACK_PLAY:
		return E_STR_ID_LOG_PB_PLAY;
	case LOG_TYPE_PLAYBACK_PAUSE:
		return E_STR_ID_LOG_PB_PAUSE;
	case LOG_TYPE_PLAYBACK_RESUME:
		return E_STR_ID_LOG_PB_RESUME;
	case LOG_TYPE_PLAYBACK_FF:
		return E_STR_ID_LOG_PB_FF;
	case LOG_TYPE_PLAYBACK_REW:
		return E_STR_ID_LOG_PB_REW;
	case LOG_TYPE_PLAYBACK_STOP:
		return E_STR_ID_LOG_PB_STOP;
		//数据备份(Backup)
	case LOG_TYPE_BACKUP_START:
		return E_STR_ID_LOG_BACKUP_START;
	case LOG_TYPE_BACKUP_COMPLETE:
		return E_STR_ID_LOG_BACKUP_COMPLETE;
	case LOG_TYPE_BACKUP_CANCEL:
		return E_STR_ID_LOG_BACKUP_CANCEL;
	case LOG_TYPE_BACKUP_FAIL:
		return E_STR_ID_LOG_BACKUP_FAIL;
		//录像检索(Search)
	case LOG_TYPE_SEARCH_TIME:
		return E_STR_ID_LOG_SEARCH_TIME;
	case LOG_TYPE_SEARCH_EVENT:
		return E_STR_ID_LOG_SEARCH_EVENT;
	case LOG_TYPE_SEARCH_FILE_MAN:
		return E_STR_ID_LOG_SEARCH_FILE_MAN;
	case LOG_TYPE_DELETE_FILE:
		return E_STR_ID_LOG_DELETE_FILE;
	case LOG_TYPE_LOCK_FILE:
		return E_STR_ID_LOG_LOCK_FILE;
	case LOG_TYPE_UNLOCK_FILE:
		return E_STR_ID_LOG_ULOCK_FILE;
	case LOG_TYPE_DELETE_PICTURE:
		return E_STR_ID_LOG_DELETE_PICTURE;
	case LOG_TYPE_LOCK_PICTURE:
		return E_STR_ID_LOG_LOCK_PICTURE;
	case LOG_TYPE_UNLOCK_PICTURE:
		return E_STR_ID_LOG_ULOCK_PICTURE;
		//查看信息(View information)
	case LOG_TYPE_VIEW_SYSTEM:
		return E_STR_ID_LOG_VIEW_SYSTEM;
	case LOG_TYPE_VIEW_EVENT:
		return E_STR_ID_LOG_VIEW_EVENT;
	case LOG_TYPE_VIEW_LOG:
		return E_STR_ID_LOG_VIEW_LOG;
	case LOG_TYPE_VIEW_NETWORK:
		return E_STR_ID_LOG_VIEW_NETWORK;
	case LOG_TYPE_VIEW_ONLINE_USER:
		return E_STR_ID_LOG_VIEW_ON_LINE_USERS;
	case LOG_TYPE_VIEW_EXPORT_LOG:
		return E_STR_ID_LOG_EXPORT_LOG;
	case LOG_TYPE_VIEW_EXPORT_EVENT:
		return E_STR_ID_LOG_EXPORT_EVENT;
		//异常信息(Error)
	case LOG_TYPE_IP_CONFLICT:
		return E_STR_ID_LOG_IP_CONFLICT;
	case LOG_TYPE_NETWORK_ERR:
		return E_STR_ID_LOG_NETWORK_ERR;
	case LOG_TYPE_DDNS_ERR:
		return E_STR_ID_LOG_DDNS_ERR;
	case LOG_TYPE_DISK_IO_ERR:
		return E_STR_ID_LOG_DISK_IO_ERR;
	case LOG_TYPE_UNKNOWN_OFF:
		return E_STR_ID_LOG_UNKNOWN_OFF;
	case LOG_TYPE_UNKNOWN_ERR:
		return E_STR_ID_LOG_UNKNOWN_ERR;
	case LOG_TYE_DISK_WARNING:
		return E_STR_ID_LOG_DISK_WARNING;
	case LOG_TYE_DISK_DISCONNECT:
		return E_STR_ID_LOG_DISK_DISCONNECT;
	case LOG_TYE_DISK_FULL:
		return E_STR_ID_DISK_FULL;
	default:
		return E_STR_ID_LOG_UNKNOWN_ERR;
	}
}


#endif
